version: '3.8'
services:
  app:
    container_name: container_app_laba3
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - site_static:/usr/share/nginx/html 

volumes:
  site_static: